all: server client Assign-2.o

# Assign-2: Assign-2.o
# 	g++ Assign-2.o -lpthread -o Assign-2

# server: server.o
# 	g++ server.o -lpthread -o server

# client: client.o
# 	g++ client.o -lpthread -o client

Assign-2.o: Assign-2.cpp
	g++ Assign-2.cpp -lpthread -o Assign-2.o

server: server.cpp
	g++ server.cpp -lpthread -o server

client: client.cpp
	g++ client.cpp -lpthread -o client