/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms_final;

import javax.swing.*;

/**
 *
 * @author Asad
 */
public class LibraryUI extends javax.swing.JFrame {
    String username;
    String password;
    Library library;
    /**
     * Creates new form LibraryUI
     */
    public LibraryUI() {
        library = new Library();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        MiddlePanel = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setBackground(new java.awt.Color(184, 216, 216));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        UpperPanel.setBackground(new java.awt.Color(228, 240, 252));

        TitleLabel.setFont(new java.awt.Font("Lato Black", 1, 30)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(46, 61, 64));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Library Management System");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(TitleLabel)
                .addGap(170, 170, 170))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(TitleLabel)
                .addGap(43, 43, 43))
        );

        getContentPane().add(UpperPanel, java.awt.BorderLayout.PAGE_START);

        MiddlePanel.setBackground(new java.awt.Color(184, 216, 216));

        UsernameLabel.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(46, 61, 64));
        UsernameLabel.setText("Username");

        UsernameField.setBackground(new java.awt.Color(228, 240, 252));
        UsernameField.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N
        UsernameField.setForeground(PasswordLabel.getForeground());

        PasswordLabel.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(46, 61, 64));
        PasswordLabel.setText("Password");

        PasswordField.setBackground(new java.awt.Color(228, 240, 252));
        PasswordField.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N

        LoginButton.setBackground(new java.awt.Color(209, 231, 255));
        LoginButton.setFont(new java.awt.Font("Lato Black", 1, 20)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(46, 61, 64));
        LoginButton.setText("Login");
        LoginButton.setBorderPainted(false);
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MiddlePanelLayout.createSequentialGroup()
                        .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameLabel)
                            .addComponent(PasswordLabel))
                        .addGap(64, 64, 64)
                        .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(MiddlePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        username = null;
        password = null;
        int result;
        boolean passwordEmpty = false;
        boolean usernameEmpty = false;
        //Library library = new Library(this);
        
        try{
            username = UsernameField.getText();
            password = String.valueOf(PasswordField.getPassword());
        }
        catch(NullPointerException e)
        {
        }
        if("".equals(username))
        {
            JOptionPane.showMessageDialog(this, "Username field cannot be empty.",  
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
            usernameEmpty = true;
        }
        if("".equals(password))
        {
            JOptionPane.showMessageDialog(this, "Password field cannot be empty.",  
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
            passwordEmpty = true;
        }
        
        result = library.login(username, password);
        if(result == 1)
        {
            JOptionPane.showMessageDialog(this, "Logged in successfully as Borrower: " + username,
"", JOptionPane.PLAIN_MESSAGE);
            BorrowerUI nextFrame = new BorrowerUI();
            nextFrame.giveValues(username, library);
            nextFrame.setVisible(true);
            this.setVisible(false);
        }
        else if(result == 2)
        {
            JOptionPane.showMessageDialog(this, "Logged in successfully as Clerk: " + username,
"", JOptionPane.PLAIN_MESSAGE);
            ClerkUI nextFrame = new ClerkUI();
            nextFrame.giveValues(username, library);
            nextFrame.setVisible(true);
            this.setVisible(false);
        }
        else if(result == 3)
        {
            JOptionPane.showMessageDialog(this, "Logged in successfully as Librarian: " + username,
"", JOptionPane.PLAIN_MESSAGE);     
            LibrarianUI nextFrame = new LibrarianUI();
            nextFrame.giveValues(username, library);
            nextFrame.setVisible(true);
            this.setVisible(false);
        }
//        {
//            DialogBoxField.setText("Success!");
//            this.dispose();
//            BorrowerUI borrower = new BorrowerUI();
//            borrower.userLoggedIn = username;
//            borrower.frontPage = this;
//            borrower.setVisible(true);
//        }
        else
        {
            JOptionPane.showMessageDialog(this, "No such user exists. Please try again!",  
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    // End of variables declaration//GEN-END:variables
}
